### ISSUE TITLE
Action don't generate failure report

### ISSUE THREAD

**Issue by reinaldocosta** [nearform/node-test-github-reporter#112]
Hi there! 

I created an sample repo to simulate my issue: 
https://github.com/reinaldocosta/node-test-reporter/

When my tests are passing, the report is created:
https://github.com/reinaldocosta/node-test-reporter/actions/runs/6423353048

But when my tests are breaking, the action ends and no report is created:
https://github.com/reinaldocosta/node-test-reporter/actions/runs/6423405450

Am I missing something?

**Comment by simoneb** [comment]
@msebastianb I thought we had fixed this in https://github.com/nearform/node-test-github-reporter/pull/105.

@reinaldocosta can you make sure you're using the latest version?

**Comment by msebastianb** [comment]
Thanks, I'll take a look.

**Comment by reinaldocosta** [comment]
@simoneb Yes, I'm using 1.1.5

**Comment by reinaldocosta** [comment]
I changed my package.json and specified `type: "module"` and now the action generated the report. 
https://github.com/reinaldocosta/node-test-reporter/actions/runs/6435828350

**Comment by simoneb** [comment]
Yes @msebastianb that sounds like a viable option

**Comment by msebastianb** [comment]
I did a more accurate analysis on the simulation repo provided and without type module it doesn't work and the parser throws errors because inside the test files imports are made using _import_ instead of _require_.
Without type module inside package.json it takes commonjs as default and if imports are made using _require_ the reporter still works as expected.
Exporting the reporter and the parser as commonjs doesn't make sense for our modules and for custom reporters in general. This is because, in the node test runner, the reporters are not depending on the type of project the tests are run on.

@reinaldocosta in addition to run the tests directly from ts files the issue https://github.com/TypeStrong/ts-node/discussions/1811 could be helpful.
